### ISSUE TITLE
check-es-shard-allocation-status.rb & Elasticsearch 7.x

### ISSUE THREAD

**Issue by tgdfool2** [sensu-plugins/sensu-plugins-elasticsearch#176]
Hi Everyone,

We are facing a similar issue as the one described under https://github.com/sensu-plugins/sensu-plugins-elasticsearch/issues/66, but this time with an Elastic 7.x cluster. Here is the output of the `check-es-shard-allocation-status.rb` command invocation:
```
Check failed to run: 400 Bad Request, ["/usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'", "/usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'", "/usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'", "/usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'", "/usr/local/lib/ruby/2.5.0/net/http.rb:910:in `start'", "/usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'", "/usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'", "/usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'", "/usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/resource.rb:51:in `get'", "/usr/local/bundle/gems/sensu-plugins-elasticsearch-4.2.2/bin/check-es-shard-allocation-status.rb:100:in `get_es_resource'", "/usr/local/bundle/gems/sensu-plugins-elasticsearch-4.2.2/bin/check-es-shard-allocation-status.rb:112:in `master?'", "/usr/local/bundle/gems/sensu-plugins-elasticsearch-4.2.2/bin/check-es-shard-allocation-status.rb:129:in `run'", "/usr/local/bundle/gems/sensu-plugin-4.0.0/lib/sensu-plugin/cli.rb:59:in `block in <class:CLI>'"]
```

Using the script from `sensu-plugins-elasticsearch (4.2.2)` gem.

Thanks in advance for your help!

**Comment by tgdfool2** [comment]
Sorry, my mistake: the `--scheme` option was missing in my command invocation.

I was expecting the default to be `https`, which is apparently not the case.
